name: format-and-lint

on:
  pull_request:
  push:
    branches: ["master", "main", "rewrite"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install poetry
          poetry install --only dev

      - name: Format with isort and black
        run: |
          poetry run isort ./
          poetry run black ./

      - name: Type check with mypy
        run: |
          poetry run mypy ./

      - name: Linting with ruff
        run: |
          poetry run ruff ./
